# Generated by Django 5.1.6 on 2026-09-17 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estudantes', '0002_estudante_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('nome', models.CharField(max_length=150)),
                ('imagem', models.ImageField(upload_to='fotos/cursos')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=12)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200)),
                ('cpf', models.CharField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('codigo', models.IntegerField(max_length=2, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('foto', models.ImageField(upload_to='fotos/cursos')),
                ('duracao', models.DecimalField(decimal_places=2, max_digits=3)),
                ('data_inicio', models.DateField(blank=True)),
                ('cargaHoraria', models.IntegerField()),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academico.departamento')),
                ('professor', models.ManyToManyField(blank=True, to='academico.professor')),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=15)),
                ('anoIngresso', models.IntegerField(max_length=4)),
                ('periodo', models.IntegerField(max_length=1)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academico.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(max_length=3)),
                ('nome', models.CharField(max_length=150)),
                ('cargaHoraria', models.IntegerField()),
                ('turno', models.CharField(max_length=10)),
                ('estudante', models.ManyToManyField(blank=True, to='estudantes.estudante')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academico.professor')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.turma')),
            ],
        ),
    ]
