# Generated by Django 6.1 on 2026-09-17 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0001_initial'),
        ('estudantes', '0003_alter_estudante_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='estudante',
            field=models.ManyToManyField(blank=True, to='estudantes.estudante'),
        ),
    ]
