# Generated by Django 5.1.6 on 2026-08-13 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.IntegerField()),
                ('nome', models.CharField(max_length=120)),
                ('telefone', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nascimento', models.DateField()),
                ('senha', models.CharField(max_length=16)),
            ],
        ),
    ]
