# Generated by Django 5.1.6 on 2026-09-03 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudantes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudante',
            name='foto',
            field=models.ImageField(null=True, upload_to='fotos/estudantes'),
        ),
    ]
