# Generated by Django 6.1 on 2026-09-17 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudantes', '0002_estudante_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudante',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
